# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nitem.proto\x12\x04item\"y\n\x07Listing\x12\x11\n\tlistingId\x18\x01 \x01(\x05\x12\x18\n\x04item\x18\x02 \x01(\x0b\x32\n.item.Item\x12\r\n\x05price\x18\x03 \x01(\x05\x12\x14\n\x0ctimeToExpire\x18\x04 \x01(\x05\x12\x1c\n\x06seller\x18\x05 \x01(\x0b\x32\x0c.item.Seller\"l\n\x06Seller\x12\x11\n\taccountId\x18\x01 \x01(\t\x12\x11\n\tclassInfo\x18\x02 \x01(\t\x12\x14\n\x07unknown\x18\x03 \x01(\x05H\x00\x88\x01\x01\x12\x11\n\x04rank\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\n\n\x08_unknownB\x07\n\x05_rank\"\x9f\x01\n\x04Item\x12\x14\n\x0citemUniqueId\x18\x01 \x01(\x04\x12\x0e\n\x06itemId\x18\x02 \x01(\t\x12)\n\rpropertyArray\x18\t \x03(\x0b\x32\x12.item.ItemProperty\x12\x10\n\x08unknown1\x18\x03 \x01(\x05\x12\x10\n\x08unknown2\x18\x04 \x01(\x05\x12\x10\n\x08unknown3\x18\x05 \x01(\x05\x12\x10\n\x08unknown4\x18\x0b \x01(\x05\"/\n\x0cItemProperty\x12\x10\n\x08property\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\"5\n\x0eMarketResponse\x12#\n\x0clistingArray\x18\x01 \x03(\x0b\x32\r.item.Listingb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'item_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LISTING._serialized_start=20
  _LISTING._serialized_end=141
  _SELLER._serialized_start=143
  _SELLER._serialized_end=251
  _ITEM._serialized_start=254
  _ITEM._serialized_end=413
  _ITEMPROPERTY._serialized_start=415
  _ITEMPROPERTY._serialized_end=462
  _MARKETRESPONSE._serialized_start=464
  _MARKETRESPONSE._serialized_end=517
# @@protoc_insertion_point(module_scope)
