# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cplayer.proto\x12\rdarkanddarker\"l\n\x06Player\x12\x11\n\taccountId\x18\x01 \x01(\t\x12\x11\n\tclassInfo\x18\x02 \x01(\t\x12\x14\n\x07unknown\x18\x03 \x01(\x05H\x00\x88\x01\x01\x12\x11\n\x04rank\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\n\n\x08_unknownB\x07\n\x05_rank\"\x11\n\x0fShortPlayerInfo\"\x13\n\x11PartyInfoResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'player_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYER._serialized_start=31
  _PLAYER._serialized_end=139
  _SHORTPLAYERINFO._serialized_start=141
  _SHORTPLAYERINFO._serialized_end=158
  _PARTYINFORESPONSE._serialized_start=160
  _PARTYINFORESPONSE._serialized_end=179
# @@protoc_insertion_point(module_scope)
