# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: s_item.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cs_item.proto\x12\tDC.Packet\">\n\rSItemProperty\x12\x16\n\x0epropertyTypeId\x18\x01 \x01(\t\x12\x15\n\rpropertyValue\x18\x02 \x01(\x05\"e\n\x05SItem\x12\x14\n\x0citemUniqueId\x18\x01 \x01(\x04\x12\x0e\n\x06itemId\x18\x02 \x01(\t\x12\x36\n\x14primaryPropertyArray\x18\x03 \x03(\x0b\x32\x18.DC.Packet.SItemPropertyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 's_item_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SITEMPROPERTY._serialized_start=27
  _SITEMPROPERTY._serialized_end=89
  _SITEM._serialized_start=91
  _SITEM._serialized_end=192
# @@protoc_insertion_point(module_scope)
